# Generated by Django 3.0.8 on 2020-12-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
